export const Data = [
  {
    id: "1",
    title: "1. Compound Interest, Keajaiban ke 8 Dunia",
    drive: "https://youtu.be/bqtgA99Lc2o?si=B7Ox5nYS-KXgNUE_",
    link: "/Halaman/page/1-financial-litracy/16/1",
    category: "Financial Litracy",
  },
  {
    id: "2",
    title: "2. Gaya Hidup Sederhana",
    drive: "https://youtu.be/NVv17m5pKVk?si=sJpMqNITrcj-XfvI",
    link: "/Halaman/page/1-financial-litracy/16/2",
    category: "Financial Litracy",
  },
  {
    id: "3",
    title: "3. Jangan Pernah Kehilangan Uang",
    drive: "https://youtu.be/ALIS8G2xkvI?si=k_t6MsVu-_pr8eKK",
    link: "/Halaman/page/1-financial-litracy/16/3",
    category: "Financial Litracy",
  },
  {
    id: "4",
    title: "4. Investasi Sebagai Bisnis",
    drive: "https://youtu.be/-tN4IcQgMqg?si=0aPnZrFi1T72GVGW",
    link: "/Halaman/page/1-financial-litracy/16/4",
    category: "Financial Litracy",
  },
  {
    id: "5",
    title: "5. Strategi Kekayaan Jangka Panjang",
    drive: "https://youtu.be/jvxWj9GUhxs?si=BB2jqC6y8HfPu6nB",
    link: "/Halaman/page/1-financial-litracy/16/5",
    category: "Financial Litracy",
  },
  {
    id: "6",
    title: "6. Avoiding Stupidity",
    drive: "https://youtu.be/HPGSPk2TIuw?si=NRjXZnUNgyDjOivz",
    link: "/Halaman/page/1-financial-litracy/16/6",
    category: "Financial Litracy",
  },
  {
    id: "7",
    title: "7. Berinvestasi Untuk Legacy",
    drive: "https://youtu.be/gOTufcwON9k?si=eFeGLDiRduZUUJzW",
    link: "/Halaman/page/1-financial-litracy/16/7",
    category: "Financial Litracy",
  },
];
