export const tradingData = [
  {
    title: "Modul 22",
    image: "/images/assetsclas.webp", 
    link: "/Halaman/page/1-financial-litracy/22",
    category: "Financial Litracy",
  },
  {
    title: "Modul 21",
    image: "/images/macroeconimi.webp", 
    link: "/Halaman/page/1-financial-litracy/21",
    category: "Financial Litracy",
  },
  {
    title: "Modul 1",
    image: "/images/Personal-Finance.jpg", 
    link: "/Halaman/page/1-financial-litracy/1",
    category: "Financial Litracy",
  },
  {
    title: "Modul 2",
    image: "/images/Rich-Mindset-VS-Poor-Mindset.jpg", 
    link: "/Halaman/page/1-financial-litracy/2",
    category: "Financial Litracy",
  },
  {
    title: "Modul 3",
    image: "/images/Membuat-Tujuan-Keuangan.jpg", 
    link: "/Halaman/page/1-financial-litracy/3",
    category: "Financial Litracy",
  },
  {
    title: "Modul 4",
    image: "/images/Membuat-Anggaran-Bulanan.jpg", 
    link: "/Halaman/page/1-financial-litracy/4",
    category: "Financial Litracy",
  },
  {
    title: "Modul 5",
    image: "/images/Mengatur-Gaji-Secara-Efektif.jpg", 
    link: "/Halaman/page/1-financial-litracy/5",
    category: "Financial Litracy",
  },
  {
    title: "Modul 6",
    image: "/images/Membongkar-Kebocoran-Keuangan.jpg", 
    link: "/Halaman/page/1-financial-litracy/6",
    category: "Financial Litracy",
  },
  {
    title: "Modul 7",
    image: "/images/Strategi-Tingkatkan-Penghasilan.jpg", 
    link: "/Halaman/page/1-financial-litracy/7",
    category: "Financial Litracy",
  },
  {
    title: "Modul 8",
    image: "/images/Utang-Produktif-VS-Konsumtif.jpg", 
    link: "/Halaman/page/1-financial-litracy/8",
    category: "Financial Litracy",
  },
  {
    title: "Modul 9",
    image: "/images/Kartu-Kredit-Secara-Bijak.jpg", 
    link: "/Halaman/page/1-financial-litracy/9",
    category: "Financial Litracy",
  },
  {
    title: "Modul 10",
    image: "/images/Snowball-VS-Avalanche.jpg", 
    link: "/Halaman/page/1-financial-litracy/10",
    category: "Financial Litracy",
  },
  {
    title: "Modul 11",
    image: "/images/Bahaya-Cicilan-Gaya-Hidup-Kredit.jpg", 
    link: "/Halaman/page/1-financial-litracy/11",
    category: "Financial Litracy",
  },
  {
    title: "Modul 12",
    image: "/images/Cara-Menentukan-Dana-Darurat.jpg", 
    link: "/Halaman/page/1-financial-litracy/12",
    category: "Financial Litracy",
  },
  {
    title: "Modul 13",
    image: "/images/Dimana-Menyimpan-Dana-Darurat.jpg", 
    link: "/Halaman/page/1-financial-litracy/13",
    category: "Financial Litracy",
  },
  {
    title: "Modul 14",
    image: "/images/Kebiasaan-Menabung.jpg", 
    link: "/Halaman/page/1-financial-litracy/14",
    category: "Financial Litracy",
  },
  {
    title: "Modul 15",
    image: "/images/capital-market.jpeg", 
    link: "/Halaman/page/1-financial-litracy/15",
    category: "Financial Litracy",
  },
  {
    title: "Modul 16",
    image: "/images/the-wealth-blueprint.jpeg", 
    link: "/Halaman/page/1-financial-litracy/16",
    category: "Financial Litracy",
  },
  {
    title: "Modul 17",
    image: "/images/the-investors-mind.jpeg", 
    link: "/Halaman/page/1-financial-litracy/17",
    category: "Financial Litracy",
  },
  {
    title: "Modul 18",
    image: "/images/bhivoral-finance.jpeg", 
    link: "/Halaman/page/1-financial-litracy/18",
    category: "Financial Litracy",
  },
  {
    title: "Modul 19",
    image: "/images/principles-of-investing.jpeg", 
    link: "/Halaman/page/1-financial-litracy/19",
    category: "Financial Litracy",
  },
  {
    title: "Modul 20",
    image: "/images/financial-accounting.jpeg", 
    link: "/Halaman/page/1-financial-litracy/20",
    category: "Financial Litracy",
  },
];
