export const Data = [
  {
    id: "1",
    title: "1. Prinsip Pertama Integritas dan Kesabaran",
    drive: "https://drive.google.com/file/d/1AOJtx9f8i5CoRTqBfZf0OqzQifH1Xqwl/view?usp=drive_link",
    link: "/Halaman/page/1-financial-litracy/17/1",
    category: "Financial Litracy",
  },
  {
    id: "2",
    title: "2. Circle of Competence",
    drive: "https://drive.google.com/file/d/19uZNZdm6C1MwjCUHSaB2x5utCbPHuzW4/view?usp=drive_link",
    link: "/Halaman/page/1-financial-litracy/17/2",
    category: "Financial Litracy",
  },
  {
    id: "3",
    title: "3. The Psychology Money",
    drive: "https://drive.google.com/file/d/17hE1JoSQDg1H6aMjsqCGUThmbU5ohD52/view?usp=drive_link",
    link: "/Halaman/page/1-financial-litracy/17/3",
    category: "Financial Litracy",
  },
  {
    id: "4",
    title: "4. Mental Models 101",
    drive: "https://drive.google.com/file/d/1u8KOLWvOvXa_UyaNF8M3zFiySsD-oJ0C/view?usp=drive_link",
    link: "/Halaman/page/1-financial-litracy/17/4",
    category: "Financial Litracy",
  },
  {
    id: "5",
    title: "5. Value VS Price",
    drive: "https://drive.google.com/file/d/1GHLRAhtHPKjKj63NGYT5Y9iU_FN81XqW/view?usp=drive_link",
    link: "/Halaman/page/1-financial-litracy/17/5",
    category: "Financial Litracy",
  },
  {
    id: "6",
    title: "6. Margin of Safety",
    drive: "https://drive.google.com/file/d/1gtNLC0JEOUsz0eAInArcSfSpfdL5yjSo/view?usp=drive_link",
    link: "/Halaman/page/1-financial-litracy/17/6",
    category: "Financial Litracy",
  },
  {
    id: "7",
    title: "7. The Long Term Mindset",
    drive: "https://drive.google.com/file/d/1Rst1fpZM2arOMNjd_tYpbxee1D4vsy-B/view?usp=drive_link",
    link: "/Halaman/page/1-financial-litracy/17/7",
    category: "Financial Litracy",
  },
];
