export const investingData = [
  {
    title: "20",
    image: "/images/financial-accounting.jpeg",
    link: "/Halaman/page/1-financial-litracy/20/1",
    category: "Financial Litracy",
  },
  {
    title: "19",
    image: "/images/principles-of-investing.jpeg",
    link: "/Halaman/page/1-financial-litracy/19/1",
    category: "Financial Litracy",
  },
  {
    title: "18",
    image: "/images/bhivoral-finance.jpeg",
    link: "/Halaman/page/1-financial-litracy/18/1",
    category: "Financial Litracy",
  },
  {
    title: "17",
    image: "/images/the-investors-mind.jpeg",
    link: "/Halaman/page/1-financial-litracy/17/1",
    category: "Financial Litracy",
  },
  {
    title: "16",
    image: "/images/the-wealth-blueprint.jpeg",
    link: "/Halaman/page/1-financial-litracy/16/1",
    category: "Financial Litracy",
  },
  {
    title: "15",
    image: "/images/capital-market.jpeg",
    link: "/Halaman/page/1-financial-litracy/15/1",
    category: "Financial Litracy",
  },
  {
    title: "14",
    image: "/images/Kebiasaan-Menabung.jpg",
    link: "/Halaman/page/1-financial-litracy/14/1",
    category: "Financial Litracy",
  },
  {
    title: "13",
    image: "/images/Dimana-Menyimpan-Dana-Darurat.jpg",
    link: "/Halaman/page/1-financial-litracy/13/1",
    category: "Financial Litracy",
  },
  {
    title: "12",
    image: "/images/Cara-Menentukan-Dana-Darurat.jpg",
    link: "/Halaman/page/1-financial-litracy/12/1",
    category: "Financial Litracy",
  },
  {
    title: "11",
    image: "/images/Bahaya-Cicilan-Gaya-Hidup-Kredit.jpg",
    link: "/Halaman/page/1-financial-litracy/11/1",
    category: "Financial Litracy",
  },
  {
    title: "10",
    image: "/images/Snowball-VS-Avalanche.jpg",
    link: "/Halaman/page/1-financial-litracy/10/1",
    category: "Financial Litracy",
  },
  {
    title: "9",
    image: "/images/Kartu-Kredit-Secara-Bijak.jpg",
    link: "/Halaman/page/1-financial-litracy/9/1",
    category: "Financial Litracy",
  },
  {
    title: "8",
    image: "/images/Utang-Produktif-VS-Konsumtif.jpg",
    link: "/Halaman/page/1-financial-litracy/8/1",
    category: "Financial Litracy",
  },
  {
    title: "7",
    image: "/images/Strategi-Tingkatkan-Penghasilan.jpg",
    link: "/Halaman/page/1-financial-litracy/7/1",
    category: "Financial Litracy",
  },
  {
    title: "6",
    image: "/images/Membongkar-Kebocoran-Keuangan.jpg",
    link: "/Halaman/page/1-financial-litracy/6/1",
    category: "Financial Litracy",
  },
  {
    title: "5",
    image: "/images/Mengatur-Gaji-Secara-Efektif.jpg",
    link: "/Halaman/page/1-financial-litracy/5/1",
    category: "Financial Litracy",
  },
  {
    title: "4",
    image: "/images/Membuat-Anggaran-Bulanan.jpg",
    link: "/Halaman/page/1-financial-litracy/4/1",
    category: "Financial Litracy",
  },
  {
    title: "3",
    image: "/images/Membuat-Tujuan-Keuangan.jpg",
    link: "/Halaman/page/1-financial-litracy/3/1",
    category: "Financial Litracy",
  },
  {
    title: "2",
    image: "/images/Rich-Mindset-VS-Poor-Mindset.jpg",
    link: "/Halaman/page/1-financial-litracy/2/1",
    category: "Financial Litracy",
  },
  {
    title: "1",
    image: "/images/Personal-Finance.jpg",
    link: "/Halaman/page/1-financial-litracy/1/1",
    category: "Financial Litracy",
  },
];
