export const Data = [
  {
    id: "1",
    title: "1. Prinsip Pertama Integritas dan Kesabaran",
    drive: "https://youtu.be/NRjk6Kij1w8?si=t-W88f3AvNh0Lymy",
    link: "/Halaman/page/1-financial-litracy/17/1",
    category: "Financial Litracy",
  },
  {
    id: "2",
    title: "2. Circle of Competence",
    drive: "https://youtu.be/EBACxlwhvoY?si=Fn21XeejqpdWW2Dp",
    link: "/Halaman/page/1-financial-litracy/17/2",
    category: "Financial Litracy",
  },
  {
    id: "3",
    title: "3. The Psychology Money",
    drive: "https://youtu.be/yXNtwYAevi4?si=nnnHcms_ioPNVWjq",
    link: "/Halaman/page/1-financial-litracy/17/3",
    category: "Financial Litracy",
  },
  {
    id: "4",
    title: "4. Mental Models 101",
    drive: "https://youtu.be/6ky79E-zS90?si=njfNAoHZo15jgu8X",
    link: "/Halaman/page/1-financial-litracy/17/4",
    category: "Financial Litracy",
  },
  {
    id: "5",
    title: "5. Value VS Price",
    drive: "https://youtu.be/TZ-0UMvACg8?si=tHDlF6msFjp_7KNE",
    link: "/Halaman/page/1-financial-litracy/17/5",
    category: "Financial Litracy",
  },
  {
    id: "6",
    title: "6. Margin of Safety",
    drive: "https://youtu.be/90mWOLsA8xQ?si=96k5YXwamnU8yAjw",
    link: "/Halaman/page/1-financial-litracy/17/6",
    category: "Financial Litracy",
  },
  {
    id: "7",
    title: "7. The Long Term Mindset",
    drive: "https://youtu.be/rnCEty1fwuU?si=EIGD1wzWzAQQNqqd",
    link: "/Halaman/page/1-financial-litracy/17/7",
    category: "Financial Litracy",
  },
];
