export const Data = [
  {
    id: "1",
    title: "1. Fundamental Analysis 101",
    drive: "https://youtu.be/Ih0tMpVJVgk?si=O05sR0LL8UN3XNUX",
    link: "/Halaman/page/1-financial-litracy/15/1",
    category: "Financial Litracy",
  },
  {
    id: "2",
    title: "2. Menganalisis Bisnis Hebat",
    drive: "https://youtu.be/27fMmjO_wds?si=cZ2e920j_6ET7Nwj",
    link: "/Halaman/page/1-financial-litracy/15/2",
    category: "Financial Litracy",
  },
  {
    id: "3",
    title: "3. Time is The Friend of The Wonderful business",
    drive: "https://youtu.be/3Zz382wFlkU?si=su4sgfG75MRQ6t2q",
    link: "/Halaman/page/1-financial-litracy/15/3",
    category: "Financial Litracy",
  },
  {
    id: "4",
    title: "4. Mr. Market is Your Servant",
    drive: "https://youtu.be/sHM0h4LFENQ?si=2oUmMVApt7cNRaUU",
    link: "/Halaman/page/1-financial-litracy/15/4",
    category: "Financial Litracy",
  },
  {
    id: "5",
    title: "5. Sektor dan Siklus - Ternak Uang",
    drive: "https://youtu.be/9mrH2yN0ITc?si=Jk2tGjcA6R8sHeW5",
    link: "/Halaman/page/1-financial-litracy/15/5",
    category: "Financial Litracy",
  },
  {
    id: "6",
    title: "6. Diversifikasi VS Konsentrasi",
    drive: "https://youtu.be/uHU_feLzq6s?si=2YvTlR5J4NckgAMt",
    link: "/Halaman/page/1-financial-litracy/15/6",
    category: "Financial Litracy",
  },
  {
    id: "7",
    title: "7. Saham Sebagai Instrumen Kekayaan",
    drive: "https://youtu.be/6Q67_LOxkYk?si=ufLZHZ13H2waDRzb",
    link: "/Halaman/page/1-financial-litracy/15/7",
    category: "Financial Litracy",
  },
];
